version: '3'

services:
  db:
    image: bitnami/postgresql:16
    container_name: api_db
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - 5433:5432
    volumes:
      - db_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d apisolid"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: api_solid
    restart: unless-stopped
    env_file: .env
    ports:
      - 3333:3333
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run seed &&
        node dist/server.js
      "

volumes:
  db_data:
